INSERT INTO public.car (mark, model) VALUES ('Audi', 'A3 III (8V)');
INSERT INTO public.car (mark, model) VALUES ('Audi', 'A3 II (8P)');
INSERT INTO public.car (mark, model) VALUES ('Audi', 'A8 III (D4)');
INSERT INTO public.car (mark, model) VALUES ('Audi', 'A8 I (D2)');
INSERT INTO public.car (mark, model) VALUES ('Mazda', '5 II (CW)');
INSERT INTO public.car (mark, model) VALUES ('Mazda', 'Axela III');
INSERT INTO public.car (mark, model) VALUES ('Mazda', 'Demio III (DE)');
INSERT INTO public.car (mark, model) VALUES ('Mazda', 'Familia Y11');
INSERT INTO public.car (mark, model) VALUES ('Mazda', '6 III (GJ) ');
INSERT INTO public.car (mark, model) VALUES ('Mercedes', 'A-Class IV (W177)');
INSERT INTO public.car (mark, model) VALUES ('Mercedes', 'C-Class IV (W205)');
INSERT INTO public.car (mark, model) VALUES ('Mercedes', 'S-Class VI (W222, C217)');
INSERT INTO public.car (mark, model) VALUES ('Mercedes', 'S-Class IV (W220) ');
INSERT INTO public.car (mark, model) VALUES ('Volkswagen', 'Golf VII');
INSERT INTO public.car (mark, model) VALUES ('Volkswagen', 'Caddy III');
INSERT INTO public.car (mark, model) VALUES ('BMW', 'X3 III (G01)');
INSERT INTO public.car (mark, model) VALUES ('BMW', '4-Series F32/F33/F36');
INSERT INTO public.car (mark, model) VALUES ('BMW', 'M6 III (F06/F13/F12)');

INSERT INTO public.admins(login, password) VALUES ('admin','admin');