INSERT INTO public.car (mark, model) VALUES ('Audi', 'Audi A3 III (8V)');
INSERT INTO public.car (mark, model) VALUES ('Audi', 'Audi A3 II (8P)');
INSERT INTO public.car (mark, model) VALUES ('Audi', 'Audi A8 III (D4)');
INSERT INTO public.car (mark, model) VALUES ('Audi', 'Audi A8 I (D2)');
INSERT INTO public.car (mark, model) VALUES ('Mazda', 'Mazda 5 II (CW)');
INSERT INTO public.car (mark, model) VALUES ('Mazda', 'Mazda Axela III');
INSERT INTO public.car (mark, model) VALUES ('Mazda', 'Mazda Demio III (DE)');
INSERT INTO public.car (mark, model) VALUES ('Mazda', 'Mazda Familia Y11');
INSERT INTO public.car (mark, model) VALUES ('Mazda', 'Mazda 6 III (GJ) ');
INSERT INTO public.car (mark, model) VALUES ('Mercedes', 'Mercedes-Benz A-Class IV (W177)');
INSERT INTO public.car (mark, model) VALUES ('Mercedes', 'Mercedes-Benz C-Class IV (W205)');
INSERT INTO public.car (mark, model) VALUES ('Mercedes', 'Mercedes-Benz S-Class VI (W222, C217)');
INSERT INTO public.car (mark, model) VALUES ('Mercedes', 'Mercedes-Benz S-Class IV (W220) ');
INSERT INTO public.car (mark, model) VALUES ('Volkswagen', 'Volkswagen Golf VII');
INSERT INTO public.car (mark, model) VALUES ('Volkswagen', 'Volkswagen Caddy III');
INSERT INTO public.car (mark, model) VALUES ('BMW', 'BMW X3 III (G01)');
INSERT INTO public.car (mark, model) VALUES ('BMW', 'BMW 4-Series F32/F33/F36');
INSERT INTO public.car (mark, model) VALUES ('BMW', 'BMW M6 III (F06/F13/F12)');